server:
  port: 8081
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory_management?currentSchema=inv_v1
    username: postgres
    password: ${POSTGRES_PWD}
