server:
  port: 8081
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: aaa
    username: postgres
    password: ${POSTGRES_PWD}
